-- ============================================
-- Fix storage buckets: make private and remove public policies
-- ============================================

-- Make mission-photos bucket private
UPDATE storage.buckets
SET public = false
WHERE id = 'mission-photos';

-- Make avatars bucket private
UPDATE storage.buckets
SET public = false
WHERE id = 'avatars';

-- Drop existing public policies for mission-photos (if they exist)
DROP POLICY IF EXISTS "Public Access Photos" ON storage.objects;
DROP POLICY IF EXISTS "Public Uploads Photos" ON storage.objects;
DROP POLICY IF EXISTS "Public Deletes Photos" ON storage.objects;

-- Drop existing public policies for avatars (if they exist)
DROP POLICY IF EXISTS "avatars_public_read" ON storage.objects;
-- Note: the avatars insert/update/delete policies are already restricted to the user's folder, so we leave them.
-- But we will drop the public read policy and replace it with a policy that allows authenticated users to read their own avatars? 
-- Actually, we are going to use signed URLs so we don't need any read policy on the bucket? 
-- We can remove all select policies and rely on signed URLs.

-- However, to be safe, we can drop all policies on the buckets and then we will not rely on bucket policies for security.
-- We will use signed URLs for all access, so we don't need any storage policies for reading.

-- But we still need policies for upload and delete to prevent unauthorized uploads/deletes.

-- Let's create a policy for mission-photos that allows authenticated users to upload and delete (we'll restrict by mission later in app logic or by using a more complex policy?).
-- For now, we allow authenticated users to upload and delete any file in the mission-photos bucket.

-- We'll create:
--   - insert: allow authenticated users
--   - delete: allow authenticated users
--   - select: we don't need a policy because we will use signed URLs (so we can leave select to no one, or we can drop the policy and not replace it)

-- However, note: if we drop the select policy, then no one can select (read) via the storage API. 
-- That's fine because we are going to use signed URLs which bypass the policy check? 
-- Actually, signed URLs are generated by the storage service and they do not rely on the select policy? 
-- The storage service will check the signed URL's signature and expiration, but not the policy? 
-- According to Supabase documentation, signed URLs bypass the policy check.

-- So we can drop the select policy entirely.

-- Let's do:

-- For mission-photos bucket:
--   Allow authenticated users to insert and delete.

-- For avatars bucket:
--   We already have policies for insert, update, delete that are restricted to the user's folder.
--   We will leave those and drop the public read policy.

-- We don't need to create a select policy for avatars because we will use signed URLs.

-- However, note: the avatars insert/update/delete policies are already in place from the previous migration.
-- We just need to drop the public read policy.

-- Let's write the migration accordingly.

-- Step 1: Drop the public policies for mission-photos
DROP POLICY IF EXISTS "Public Access Photos" ON storage.objects;
DROP POLICY IF EXISTS "Public Uploads Photos" ON storage.objects;
DROP POLICY IF EXISTS "Public Deletes Photos" ON storage.objects;

-- Step 2: Drop the public policy for avatars
DROP POLICY IF EXISTS "avatars_public_read" ON storage.objects;

-- Step 3: Create an insert policy for mission-photos (allow authenticated users)
CREATE POLICY "mission_photos_insert_authenticated" ON storage.objects
    FOR INSERT TO authenticated
    WITH CHECK (bucket_id = 'mission-photos');

-- Step 4: Create a delete policy for mission-photos (allow authenticated users)
CREATE POLICY "mission_photos_delete_authenticated" ON storage.objects
    FOR DELETE TO authenticated
    USING (bucket_id = 'mission-photos');

-- Note: We do not create a select policy because we will use signed URLs.

-- For avatars, we already have the insert, update, delete policies that are user-restricted (from the previous migration).
-- We do not need to change them.
